#!/usr/bin/env python3
"""
Helper script to extract Firebase configuration from google-services.json
and generate the firebase_options.dart file.

Usage:
    python extract_firebase_config.py

Make sure google-services.json is in android/app/ directory.
"""

import json
import os

def extract_config():
    # Path to google-services.json
    json_path = os.path.join('android', 'app', 'google-services.json')
    
    if not os.path.exists(json_path):
        print("❌ Error: google-services.json not found!")
        print(f"   Expected location: {json_path}")
        print("\n📥 Please download google-services.json from Firebase Console")
        print("   and place it in android/app/ directory")
        return
    
    # Read the JSON file
    with open(json_path, 'r') as f:
        data = json.load(f)
    
    # Extract values
    project_id = data['project_info']['project_id']
    project_number = data['project_info']['project_number']
    storage_bucket = data['project_info'].get('storage_bucket', f"{project_id}.appspot.com")
    
    # Get the first client (usually there's only one)
    client = data['client'][0]
    app_id = client['client_info']['mobilesdk_app_id']
    api_key = client['api_key'][0]['current_key']
    
    print("✅ Successfully extracted Firebase configuration!")
    print("\n" + "="*60)
    print("Firebase Configuration Values:")
    print("="*60)
    print(f"Project ID:        {project_id}")
    print(f"App ID:            {app_id}")
    print(f"API Key:           {api_key}")
    print(f"Messaging Sender:  {project_number}")
    print(f"Storage Bucket:    {storage_bucket}")
    print("="*60)
    
    # Generate firebase_options.dart content
    dart_content = f"""// File generated by extract_firebase_config.py
// Do not edit manually

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {{
  static FirebaseOptions get currentPlatform {{
    if (kIsWeb) {{
      return web;
    }}
    switch (defaultTargetPlatform) {{
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }}
  }}

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '{api_key}',
    appId: '{app_id}',
    messagingSenderId: '{project_number}',
    projectId: '{project_id}',
    authDomain: '{project_id}.firebaseapp.com',
    storageBucket: '{storage_bucket}',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '{api_key}',
    appId: '{app_id}',
    messagingSenderId: '{project_number}',
    projectId: '{project_id}',
    storageBucket: '{storage_bucket}',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '{api_key}',
    appId: '{app_id}',
    messagingSenderId: '{project_number}',
    projectId: '{project_id}',
    storageBucket: '{storage_bucket}',
    iosBundleId: 'com.example.otpPhoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '{api_key}',
    appId: '{app_id}',
    messagingSenderId: '{project_number}',
    projectId: '{project_id}',
    storageBucket: '{storage_bucket}',
    iosBundleId: 'com.example.otpPhoneAuth',
  );
}}
"""
    
    # Write to firebase_options.dart
    output_path = os.path.join('lib', 'firebase_options.dart')
    with open(output_path, 'w') as f:
        f.write(dart_content)
    
    print(f"\n✅ Generated {output_path}")
    print("\n🎉 Firebase configuration complete!")
    print("\nNext steps:")
    print("1. Get SHA-1: cd android && .\\gradlew.bat signingReport")
    print("2. Add SHA-1 to Firebase Console")
    print("3. Enable Phone Authentication in Firebase Console")
    print("4. Run: flutter run")

if __name__ == '__main__':
    try:
        extract_config()
    except Exception as e:
        print(f"❌ Error: {e}")
        print("\nPlease make sure:")
        print("1. google-services.json is in android/app/ directory")
        print("2. The file is valid JSON")
        print("3. You're running this script from the project root")
